spring:
  profiles:
    active: dev1

---
spring:
  profiles: dev1
  application:
    name: microservicecloud-config-dev

---
spring:
  profiles: test1
  application:
    name: microservicecloud-config-test